### ISSUE TITLE
Remove `originalPaths` from `collectWarningsFromSarif` method in WarnPlugin

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/save#355]
originalPaths  - is useless and can be replaced by a path from `originalPath` , as method `collectWarningsFromSarif ` already has `originalPath` inside:

```
    originalPath: Path,
    originalPaths: List<Path>,
```

As we see it. `originalPaths` is not needed and can be replaced by something else. 

This can be tested by `SarifWarningAdapterTest.kt` - tests are already in place. The be running on `examples/kotlin-diktat/sarif` directory, detect and get all warnings from `save-warnings.sarif` file.

Right now the logic is the following: 
- we try to get EXPECTED warnings from the SARIF input:
```
        val expectedWarningsMap: WarningMap = copyPaths.zip(originalPaths).associate { (copyPath, originalPath) ->
            val warningsForCurrentPath =
                    copyPath.collectExpectedWarningsWithLineNumbers(warnPluginConfig, generalConfig, originalPaths, originalPath)
            copyPath.name to warningsForCurrentPath
        }
```
- for each `originalPath` we also provide ALL `originalPaths`  to `collectExpectedWarningsWithLineNumbers`. But it looks useless

**Comment by RishiKumarRay** [comment]
If You're not doing , can you assign it to me?

**Comment by akuleshov7** [comment]
@RishiKumarRay sure, welcome!

**Comment by akuleshov7** [comment]
@petertrr can guide and describe the logic

**Comment by kgevorkyan** [comment]
@akuleshov7 As I see the the `originalPath` is not needed and not the `originalPaths`, isn't it?

`originalPath` removed in https://github.com/analysis-dev/save/pull/365, which probably can close this issue too

**Comment by akuleshov7** [comment]
@kgevorkyan yes, good, thank you
